"""notice comment user post model

Revision ID: 122551d82aec
Revises: 
Create Date: 2019-04-11 03:24:25.717468

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '122551d82aec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notice',
                    sa.Column('deleted', sa.Boolean(), nullable=False),
                    sa.Column('created_time', sa.Float(), nullable=True),
                    sa.Column('updated_time', sa.Float(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False, comment='id'),
                    sa.Column('title', sa.String(length=20), nullable=False),
                    sa.Column('content', sa.String(length=256), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('deleted', sa.Boolean(), nullable=False),
                    sa.Column('created_time', sa.Float(), nullable=True),
                    sa.Column('updated_time', sa.Float(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False, comment='id'),
                    sa.Column('login', sa.String(length=20), nullable=True, comment='user name'),
                    sa.Column('nickname', sa.String(length=20), nullable=True, comment='user name'),
                    sa.Column('password', sa.String(length=128), nullable=True, comment='password'),
                    sa.Column('role', mysql.ENUM('admin', 'user'), nullable=False, comment='user type'),
                    sa.Column('email', sa.String(length=20), nullable=True, comment='email'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('comments',
                    sa.Column('deleted', sa.Boolean(), nullable=False),
                    sa.Column('created_time', sa.Float(), nullable=True),
                    sa.Column('updated_time', sa.Float(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False, comment='id'),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('content', sa.String(length=256), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('posts',
                    sa.Column('deleted', sa.Boolean(), nullable=False),
                    sa.Column('created_time', sa.Float(), nullable=True),
                    sa.Column('updated_time', sa.Float(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('type', mysql.ENUM('lost', 'found'), nullable=True, comment='文章类型'),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('content', sa.Text(), nullable=True, comment='留言内容'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('attendance_post_rel',
                    sa.Column('deleted', sa.Boolean(), nullable=False),
                    sa.Column('created_time', sa.Float(), nullable=True),
                    sa.Column('updated_time', sa.Float(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('pid', sa.Integer(), nullable=False),
                    sa.Column('path', sa.String(length=128), nullable=True),
                    sa.ForeignKeyConstraint(['pid'], ['posts.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance_post_rel')
    op.drop_table('posts')
    op.drop_table('comments')
    op.drop_table('users')
    op.drop_table('notice')
    # ### end Alembic commands ###
