"""[REM] 移除附件表

Revision ID: 1d5a8f532b2e
Revises: 966d138b28de
Create Date: 2019-05-05 12:46:15.528590

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d5a8f532b2e'
down_revision = '966d138b28de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance_post_rel')
    op.alter_column('comments', 'deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=False)
    op.alter_column('likes', 'deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=False)
    op.alter_column('notices', 'deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=False)
    op.add_column('posts', sa.Column('image', sa.String(length=256), nullable=True, comment='图片路径'))
    op.alter_column('posts', 'deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=False)
    op.alter_column('users', 'deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'deleted',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=False)
    op.alter_column('posts', 'deleted',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=False)
    op.drop_column('posts', 'image')
    op.alter_column('notices', 'deleted',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=False)
    op.alter_column('likes', 'deleted',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=False)
    op.alter_column('comments', 'deleted',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=False)
    op.create_table('attendance_post_rel',
                    sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
                    sa.Column('created_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('updated_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
                    sa.Column('pid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.Column('path', mysql.VARCHAR(collation='utf8mb4_general_ci', length=128), nullable=True),
                    sa.ForeignKeyConstraint(['pid'], ['posts.id'], name='attendance_post_rel_ibfk_1'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_general_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    # ### end Alembic commands ###
