"""添加点赞表和字段注释

Revision ID: 2769a8b65b6f
Revises: 7f87305d23bb
Create Date: 2019-05-02 19:14:13.560420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2769a8b65b6f'
down_revision = '7f87305d23bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
                    sa.Column('deleted', sa.Boolean(), nullable=False),
                    sa.Column('created_time', sa.Integer(), nullable=True),
                    sa.Column('updated_time', sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False, comment='主键'),
                    sa.Column('post_id', sa.Integer(), nullable=False, comment='post表外键'),
                    sa.Column('user_id', sa.Integer(), nullable=False, comment='user表外键'),
                    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.alter_column('attendance_post_rel', 'deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=False)
    op.alter_column('comments', 'deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=False)
    op.alter_column('comments', 'id',
                    existing_type=mysql.INTEGER(display_width=11),
                    comment='主键',
                    existing_nullable=False,
                    existing_comment='id',
                    autoincrement=True)
    op.alter_column('comments', 'post_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    comment='post表外键ID',
                    existing_nullable=False)
    op.alter_column('comments', 'user_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    comment='user表外键ID',
                    existing_nullable=False)
    op.alter_column('notices', 'content',
                    existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=256),
                    comment='公告内容',
                    existing_nullable=False)
    op.alter_column('notices', 'deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=False)
    op.alter_column('notices', 'title',
                    existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
                    comment='公告标题',
                    existing_nullable=False)
    op.add_column('posts', sa.Column('contact', sa.String(length=20), nullable=True, comment='联系人'))
    op.add_column('posts', sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'))
    op.alter_column('posts', 'deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=False)
    op.alter_column('posts', 'type',
                    existing_type=mysql.ENUM('lost', 'found', charset='utf8mb4', collation='utf8mb4_general_ci'),
                    type_=mysql.ENUM('lost', 'found', 'people'),
                    existing_comment='文章类型',
                    existing_nullable=True)
    op.alter_column('posts', 'user_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=True,
                    comment='用户ID')
    op.alter_column('users', 'deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=False)
    op.alter_column('users', 'id',
                    existing_type=mysql.INTEGER(display_width=11),
                    comment='主键',
                    existing_nullable=False,
                    existing_comment='id',
                    autoincrement=True)
    op.alter_column('users', 'login',
                    existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
                    comment='账号ID',
                    existing_comment='user name',
                    existing_nullable=True)
    op.alter_column('users', 'nickname',
                    existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
                    comment='昵称',
                    existing_comment='user name',
                    existing_nullable=True)
    op.alter_column('users', 'password',
                    existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
                    comment='密码',
                    existing_comment='password',
                    existing_nullable=True)
    op.alter_column('users', 'role',
                    existing_type=mysql.ENUM('admin', 'user', collation='utf8mb4_general_ci'),
                    comment='用户类型',
                    existing_comment='user type',
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
                    existing_type=mysql.ENUM('admin', 'user', collation='utf8mb4_general_ci'),
                    comment='user type',
                    existing_comment='用户类型',
                    existing_nullable=False)
    op.alter_column('users', 'password',
                    existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
                    comment='password',
                    existing_comment='密码',
                    existing_nullable=True)
    op.alter_column('users', 'nickname',
                    existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
                    comment='user name',
                    existing_comment='昵称',
                    existing_nullable=True)
    op.alter_column('users', 'login',
                    existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
                    comment='user name',
                    existing_comment='账号ID',
                    existing_nullable=True)
    op.alter_column('users', 'id',
                    existing_type=mysql.INTEGER(display_width=11),
                    comment='id',
                    existing_comment='主键',
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('users', 'deleted',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=False)
    op.alter_column('posts', 'user_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=False,
                    comment=None,
                    existing_comment='用户ID')
    op.alter_column('posts', 'type',
                    existing_type=mysql.ENUM('lost', 'found', 'people'),
                    type_=mysql.ENUM('lost', 'found', charset='utf8mb4', collation='utf8mb4_general_ci'),
                    existing_comment='文章类型',
                    existing_nullable=True)
    op.alter_column('posts', 'deleted',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=False)
    op.drop_column('posts', 'phone')
    op.drop_column('posts', 'contact')
    op.alter_column('notices', 'title',
                    existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
                    comment=None,
                    existing_comment='公告标题',
                    existing_nullable=False)
    op.alter_column('notices', 'deleted',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=False)
    op.alter_column('notices', 'content',
                    existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=256),
                    comment=None,
                    existing_comment='公告内容',
                    existing_nullable=False)
    op.alter_column('comments', 'user_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    comment=None,
                    existing_comment='user表外键ID',
                    existing_nullable=False)
    op.alter_column('comments', 'post_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    comment=None,
                    existing_comment='post表外键ID',
                    existing_nullable=False)
    op.alter_column('comments', 'id',
                    existing_type=mysql.INTEGER(display_width=11),
                    comment='id',
                    existing_nullable=False,
                    existing_comment='主键',
                    autoincrement=True)
    op.alter_column('comments', 'deleted',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=False)
    op.alter_column('attendance_post_rel', 'deleted',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=False)
    op.drop_table('likes')
    # ### end Alembic commands ###
