"""post表添加寻人类型和手机号联系人字段 添加点赞表

Revision ID: 7f87305d23bb
Revises: 968d535d10cf
Create Date: 2019-04-25 14:17:52.719714

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f87305d23bb'
down_revision = '968d535d10cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('notice', 'notices')
    op.alter_column('attendance_post_rel', 'deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=False)
    op.add_column('comments', sa.Column('post_id', sa.Integer(), nullable=False))
    op.alter_column('comments', 'deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=False)
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'])
    op.add_column('posts', sa.Column('contact', sa.String(length=20), nullable=True, comment='联系人'))
    op.add_column('posts', sa.Column('phone', sa.String(length=20), nullable=True))
    op.alter_column('posts', 'deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=False)
    op.alter_column('posts', 'type',
                    existing_type=mysql.ENUM('lost', 'found', charset='utf8mb4', collation='utf8mb4_general_ci'),
                    type_=mysql.ENUM('lost', 'found', 'people'),
                    existing_comment='文章类型',
                    existing_nullable=True)
    op.alter_column('posts', 'user_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=True,
                    comment='用户ID')
    op.alter_column('users', 'deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'deleted',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=False)
    op.alter_column('posts', 'user_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=False,
                    comment=None,
                    existing_comment='用户ID')
    op.alter_column('posts', 'type',
                    existing_type=mysql.ENUM('lost', 'found', 'people'),
                    type_=mysql.ENUM('lost', 'found', charset='utf8mb4', collation='utf8mb4_general_ci'),
                    existing_comment='文章类型',
                    existing_nullable=True)
    op.alter_column('posts', 'deleted',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=False)
    op.drop_column('posts', 'phone')
    op.drop_column('posts', 'contact')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.alter_column('comments', 'deleted',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=False)
    op.drop_column('comments', 'post_id')
    op.alter_column('attendance_post_rel', 'deleted',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=False)
    op.rename_table('notices', 'notice')
    # ### end Alembic commands ###
